version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./projects:/app/projects
      - ./cache:/app/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8001:8000"
    volumes:
      - ./projects:/app/projects
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 