version: '3.8'

# Make sure DOCKERHUB_USERNAME and APP_VERSION are set in your environment
# before running docker-compose commands.
# Example:
# export DOCKERHUB_USERNAME=your_dockerhub_username
# export APP_VERSION=v1.0.0

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=part_finder
      - POSTGRES_PASSWORD=part_finder
      - POSTGRES_DB=part_finder
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://part_finder:part_finder@db:5432/part_finder
      - CACHE_DIR=/app/cache
      - PINECONE_API_KEY=${PINECONE_DB_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX=mouserparts
      - MOUSER_API_KEY=${MOUSER_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./cache:/app/cache
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=pcb_part_finder.web.server
      - FLASK_ENV=development
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: