apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: part-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: us-central1-docker.pkg.dev/bompartfinder/part-finder-repo/web:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: part-finder-config
        - secretRef:
            name: part-finder-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: part-finder
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP 